# Generated by Django 5.2.5 on 2025-09-02 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('ADMIN', 'Administrateur'), ('GESTION', 'Gestionnaire')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_equipe1', models.CharField(max_length=100)),
                ('nom_equipe2', models.CharField(max_length=100)),
                ('stadium', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('division', models.CharField(max_length=50)),
                ('prix_a', models.DecimalField(decimal_places=2, help_text='Prix pour la catégorie A', max_digits=10)),
                ('prix_b', models.DecimalField(decimal_places=2, help_text='Prix pour la catégorie B', max_digits=10)),
                ('agent_createur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programmes_crees', to='ticketing.agent')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation', models.DateTimeField(auto_now_add=True)),
                ('nombre_billets', models.PositiveIntegerField()),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.programme')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('mode_paiement', models.CharField(default='Google Pay', max_length=50)),
                ('payment_token', models.CharField(help_text='ID de transaction retourné par le processeur de paiement', max_length=255)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ticketing.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='Spectateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(max_length=100)),
                ('num_phone', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='spectateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.spectateur'),
        ),
    ]
